[env]

CC = "/home/ivan/workspace/SDK-B288/usr/bin/arm-obreey-linux-gnueabi-gcc"
CXX = "/home/ivan/workspace/SDK-B288/usr/bin/arm-obreey-linux-gnueabi-g++"
QT_INCLUDE_PATH = "/home/ivan/workspace/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/ebrmain/include"
QT_LIBRARY_PATH = "/home/ivan/workspace/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/ebrmain/lib"
PATH = "/home/ivan/workspace/SDK-B288/usr/bin:/home/ivan/.cargo/bin:~/apps/giteye:~/apps/giteye:~/apps/giteye:~/apps/giteye:/home/ivan/.cargo/bin:/home/ivan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
